# Generated by Django 3.0.1 on 2022-01-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=255)),
                ('productprice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('productquantity', models.IntegerField(max_length=10)),
            ],
        ),
    ]
