# Generated by Django 3.0.1 on 2022-01-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productquantity',
            field=models.IntegerField(),
        ),
    ]
